### ISSUE TITLE
Tidak dapat menampilkan yang harusnya di tampilkan

### ISSUE THREAD

**Issue by Xayyaa** [xeizer/surat#3]
![111111111111](https://user-images.githubusercontent.com/97872059/152466088-1b3be243-9091-4db7-97a8-4198e4bb3da7.jpeg)

**Comment by xeizer** [comment]
coba cek di layouts... kalo bisa pake 
assets

**Comment by xeizer** [comment]
Seharusnya sudah bisa, Kalo QC udah cek, dan masalah itu sudah selesai tekan tombol CLOSE atau TUTUP warna HIJAU ya, untuk menutupi kasus error
