### ISSUE TITLE
menu edit surat masuk tidak sesuai dgn yg seharusnya

### ISSUE THREAD

**Issue by Xayyaa** [xeizer/surat#5]
![00](https://user-images.githubusercontent.com/97872059/153105292-f241ba5a-a0c5-443d-92ca-d3cba2a7fa38.jpeg)

**Comment by xeizer** [comment]
maksudnya ???

**Comment by ronnyaprilianto** [comment]
icon icon nya tu tidak muncul pa
![Screenshot 2022-02-16 083627](https://user-images.githubusercontent.com/97420605/154179676-5a2cd3f3-850b-4706-80f5-9d7a137645c3.png)
k

**Comment by ronnyaprilianto** [comment]
icon nya tu tidak muncul gitu pak
![Screenshot 2022-02-16 083627](https://user-images.githubusercontent.com/97420605/154179830-ce377010-52b3-4803-9692-05c68e614ab4.png)
kek gni
